// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// IncrementalProgressItem represents an element of the numeric sequence
type IncrementalProgressItem struct {
	// Index contains item position in sequence.
	Index int `json:"index"`
	// Value is the item value.
	Value float64 `json:"value"`
	// Increment is the difference between next and current item value.
	Increment float64 `json:"increment"`
}

// ProgressionQuery provides fields to query progressions.
type ProgressionQuery struct {
	// Percentage returns progression with growing increment in absolute values,
	// but the growth is fixed and represents the percentage.
	Percentage []*IncrementalProgressItem `json:"percentage"`
	// Immutable returns sequense where all items is the same as the first one.
	Immutable []*IncrementalProgressItem `json:"immutable"`
}
