// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IncrementalProgressItem struct {
	// Item position in sequence
	Index int `json:"index"`
	// Item value
	Value float64 `json:"value"`
	// An absolute value of difference between next and current item value
	Increment float64 `json:"increment"`
}

// Queries which compute progrssions
type ProgressionRootQuery struct {
	// Returns progression with growing increment in absolute values,
	// but the growth is fixed and represents the percentage.
	Percentage []*IncrementalProgressItem `json:"percentage"`
	Immutable  []*IncrementalProgressItem `json:"immutable"`
}
